# Generated by Django 4.1 on 2023-08-13 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bookinfo',
            table='book_info',
        ),
        migrations.AlterModelTable(
            name='heroinfo',
            table='hero_info',
        ),
    ]
